Fix yaml install
ispras/oss-sydr-fuzz pull request #128
Opened 2022-12-22 10:32 UTC by hkctkuy

2022-12-22 10:36 UTC, SweetVishnya requested changes

2022-12-22 10:36 UTC, SweetVishnya commented on projects/ruamel-yaml/Dockerfile
> +RUN hg clone http://hg.code.sf.net/p/ruamel-yaml/code ruamel-yaml
checkout commit (revision)

2022-12-23 08:54 UTC, hkctkuy commented on projects/ruamel-yaml/Dockerfile
> +RUN hg clone http://hg.code.sf.net/p/ruamel-yaml/code ruamel-yaml
Done

2022-12-23 11:05 UTC, SweetVishnya approved these changes

2022-12-23 11:05 UTC, merged