Add ultrajson
ispras/oss-sydr-fuzz pull request #131
Opened 2022-12-29 13:17 UTC by hkctkuy

2023-01-17 09:31 UTC, PaDarochek requested changes

2023-01-17 09:31 UTC, PaDarochek commented on projects/ultrajson/Dockerfile
> +# Modifications copyright (C) 2022 ISP RAS
2023 здесь и далее

2023-01-17 09:31 UTC, PaDarochek commented on projects/ultrajson/hypothesis_structured_fuzzer.py
> +#!/usr/bin/python3
Если в обертку нужно только добавить шебанг, можно это сделать при сборке докера и не хранить саму обертку. Здесь и далее

2023-01-18 13:37 UTC, kobrineli commented on projects/ultrajson/hypothesis_structured_fuzzer.py
> +#!/usr/bin/python3
это обертки из oss-fuzz, их нет в ultrajson

2023-01-26 09:29 UTC, hkctkuy commented on projects/ultrajson/Dockerfile
> +# Modifications copyright (C) 2022 ISP RAS
Done

2023-01-26 15:08 UTC, kobrineli approved these changes

2023-01-26 15:56 UTC, PaDarochek approved these changes

2023-01-26 15:57 UTC, merged