Dev/headshog
ispras/oss-sydr-fuzz pull request #145
Opened 2023-02-06 15:03 UTC by headshog

2023-02-06 15:09 UTC, kobrineli commented on projects/lighttpd/Dockerfile
> +#
add `# Modifications copyright (C) 2023 ISP RAS` after the first line

2023-02-06 15:09 UTC, kobrineli commented on projects/lighttpd/Dockerfile
> +FROM sydr/ubuntu20.04-sydr-fuzz
new line after this line

2023-02-06 15:13 UTC, kobrineli commented on projects/lighttpd/Dockerfile
> +RUN apt-get update && apt-get install -y libz-dev libpcre2-dev libtool pkg-config autoconf && apt-get install unzip
remove this line, because all these tools, that are necessary, are already installed in sydr/ubuntu20.04-sydr-fuzz

2023-02-06 15:13 UTC, kobrineli commented on projects/lighttpd/Dockerfile
> +RUN git init
remove this line

2023-02-06 15:15 UTC, kobrineli commented on projects/lighttpd/Dockerfile
> +COPY fuzz_* /
instead of 2 copies you can do `COPY build.sh fuzz_* /`

2023-02-06 15:19 UTC, kobrineli commented on projects/lighttpd/README.md
> +lighttpd a secure, fast, compliant and very flexible web-server
you can leave only the first sentence and probably add `is` after `lighttpd`

2023-02-06 15:20 UTC, kobrineli commented on projects/lighttpd/README.md
> +    $ sudo docker run --rm -v `pwd`:/fuzz -it oss-sydr-fuzz-lighttpd /bin/bash
sudo docker run --privileged --network host -v /etc/localtime:/etc/localtime:ro --rm -it -v $PWD:/fuzz oss-sydr-fuzz-lighttpd /bin/bash

2023-02-06 15:21 UTC, kobrineli commented on projects/lighttpd/README.md
> +    # sydr-fuzz -merge=1 /corpus_minimized /corpus
sydr-fuzz cmin

2023-02-06 15:22 UTC, kobrineli commented on projects/lighttpd/README.md
> +
add `Change directory to /fuzz:` section

2023-02-06 15:23 UTC, kobrineli commented on projects/lighttpd/README.md
> +    # llvm-profdata merge --input-files=cov.lst -o cov.profdata
`sydr-fuzz cov-report` instead all of this

2023-02-06 15:24 UTC, kobrineli commented on projects/lighttpd/build.sh
> +#
add `# Modifications copyright (C) 2023 ISP RAS` after the second line

2023-02-06 15:26 UTC, kobrineli commented on projects/lighttpd/fuzz_burl.c
> +void run_burl_normalize (buffer *psrc, buffer *ptmp,
extra space here in the end

2023-02-06 15:26 UTC, kobrineli commented on projects/lighttpd/fuzz_burl.c
> +						int flags, int line, const char *in,
extra space in the end

2023-02-06 15:26 UTC, kobrineli commented on projects/lighttpd/fuzz_burl.c
> +    return 0;
extra spaces here in the end

2023-02-06 15:27 UTC, kobrineli commented on projects/lighttpd/fuzz_burl_sydr.c
> +void run_burl_normalize (buffer *psrc, buffer *ptmp,
extra space

2023-02-06 15:27 UTC, kobrineli commented on projects/lighttpd/fuzz_burl_sydr.c
> +						int flags, int line, const char *in,
extra space

2023-02-06 15:27 UTC, kobrineli commented on projects/lighttpd/fuzz_burl_sydr.c
> +    return 0;
extra spaces

2023-02-06 16:16 UTC, kobrineli requested changes

2023-02-06 16:16 UTC, kobrineli commented on projects/lighttpd/README.md
> +
Add 'Unzip sydr' section as in `libjpeg`

2023-02-06 16:20 UTC, SweetVishnya requested changes

2023-02-06 16:20 UTC, SweetVishnya commented on projects/lighttpd/sydr-fuzz.toml
> +[sydr]
Add license

2023-02-06 16:20 UTC, SweetVishnya commented on projects/lighttpd/sydr-fuzz.toml
> +args = "-close_fd_mask=3 /corpus"
remove close_fd_mask

2023-02-06 16:27 UTC, kobrineli requested changes

2023-02-06 16:27 UTC, kobrineli commented on projects/lighttpd/README.md
> +Unzip Sydr (`sydr.zip`) in `projects/libjpeg` directory:
libjpeg -> lighttpd

2023-02-06 16:27 UTC, kobrineli commented on projects/lighttpd/build.sh
> +./autogen.sh
extra space

2023-02-06 19:31 UTC, kobrineli requested changes

2023-02-06 19:31 UTC, kobrineli commented on projects/lighttpd/sydr-fuzz.toml
> +# Copyright 2022 ISP RAS
2022 -> 2023

2023-02-06 19:31 UTC, kobrineli commented on projects/lighttpd/fuzz_burl_sydr.c
> +/* Copyright 2021 Google LLC
Remove this file

2023-02-06 19:40 UTC, kobrineli approved these changes

2023-02-07 09:55 UTC, SweetVishnya approved these changes

2023-02-07 09:55 UTC, merged