fresh commit for ndpi project
ispras/oss-sydr-fuzz pull request #179
Opened 2023-05-25 18:45 UTC by headshog

2023-05-25 19:05 UTC, koltiradw commented
Hi! U can also add [fuzz_tls_certificate](https://github.com/ntop/nDPI/blob/dev/fuzz/fuzz_tls_certificate.c) target.

2023-05-25 20:07 UTC, SweetVishnya requested changes
@headshog, can you add new targets as @koltiradw suggested?

2023-05-26 08:28 UTC, headshog commented
> @headshog, can you add new targets as @koltiradw suggested?

Yes, okay

2023-05-26 11:13 UTC, anfedotoff approved these changes

2023-05-26 12:17 UTC, kobrineli requested changes

2023-05-26 12:27 UTC, headshog commented on projects/ndpi/load_sydr_tls_certificate.c
> +}
done

2023-05-26 12:28 UTC, merged