add libcue
ispras/oss-sydr-fuzz pull request #212
Opened 2023-10-10 08:57 UTC by koltiradw

2023-10-10 09:57 UTC, kobrineli requested changes

2023-10-10 09:57 UTC, kobrineli commented on projects/libcue/fuzz_cue_parse_string.c
> +#include <stdlib.h>
add license

2023-10-11 10:35 UTC, apach301 requested changes

2023-10-11 10:35 UTC, apach301 commented on projects/libcue/fuzz_cue_parse_string.c
> +  Cd *cd = cue_parse_string (fuzz_data);
Extra space

2023-10-11 10:35 UTC, apach301 commented on projects/libcue/build.sh
> +cmake .. -DCMAKE_C_COMPILER=$CC \
Duplicate `..` here and in following cmake commands

2023-10-13 10:18 UTC, apach301 approved these changes

2023-10-13 10:26 UTC, kobrineli requested changes

2023-10-13 10:26 UTC, kobrineli commented on projects/libcue/build.sh
> +#!/bin/bash -eu
move shebang to the first line

2023-10-13 10:28 UTC, kobrineli requested changes

2023-10-13 10:28 UTC, kobrineli commented on projects/libcue/build.sh
> +TARGET_CFLAGS="-fprofile-instr-generate -fcoverage-mapping"
better use `-g` here as well

2023-10-13 10:40 UTC, kobrineli approved these changes

2023-10-13 10:40 UTC, merged