Update revs
ispras/oss-sydr-fuzz pull request #214
Opened 2023-11-15 05:32 UTC by koltiradw

2023-11-16 04:17 UTC, koltiradw commented
I`m waiting mass rebuild on my local machine....

2023-11-16 09:31 UTC, apach301 requested changes

2023-11-16 09:31 UTC, apach301 commented on projects/ndpi/build.sh
>  $CC $CFLAGS -I $INCLUDE_DIR -I /nDPI/example /nDPI/load_sydr_ndpi_reader.c /nDPI/fuzz/fuzz_common_code.c /nDPI/example/reader_util.c $LIB_DIR/libndpi.a /libpcap-1.9.1/libpcap.a /json-c/sydr/libjson-c
`fuzz_ndpi_reader` and `fuzz_process_packet` get updated in repo, while corresponding Sydr wrappers stay unchanged.
Why don't build them the same way like `quic_get_crypto` and `tls_certificate` - without separate `load_sydr_*` file?

2023-11-16 11:07 UTC, apach301 requested changes

2023-11-16 11:08 UTC, apach301 commented
Also, why sydr and coverage targets prefixed with `load_`?

2023-11-17 13:28 UTC, koltiradw commented
@apach301
Iam need a few days for resolve current issues and for update other projects.

2024-03-20 11:32 UTC, koltiradw commented
@apach301
I'll close the PR for now. I'll be back in an unspecified time.

2024-03-20 11:32 UTC, closed without merging