Fmt
ispras/oss-sydr-fuzz pull request #22
Opened 2022-03-05 12:26 UTC by xcoldhandsx

2022-03-05 17:37 UTC, SweetVishnya requested changes

2022-03-05 17:37 UTC, SweetVishnya commented on projects/fmt/Dockerfile
> +RUN apt-get update && apt-get install -y ninja-build
ninja is already in base container

2022-03-05 17:37 UTC, SweetVishnya commented on projects/fmt/build.sh
> +cmake --build .
parallel build

2022-03-05 17:37 UTC, SweetVishnya commented on projects/fmt/build.sh
> +# Sydr
clean build dir?

2022-03-05 17:37 UTC, SweetVishnya commented on projects/fmt/build.sh
> +cmake --build .
build in parallel

2022-03-05 17:37 UTC, SweetVishnya commented on projects/fmt/build.sh
> +# Coverage
clean build

2022-03-05 17:37 UTC, SweetVishnya commented on projects/fmt/build.sh
> +cmake --build .
build in parallel

2022-03-05 17:37 UTC, SweetVishnya commented on projects/fmt/build.sh
> +mkdir fuzzers
no need to mkdir fuzzers sydr cov

2022-03-05 17:37 UTC, SweetVishnya commented on projects/fmt/build.sh
> +cp -r bin ./fuzzers
cp -r bin ../fuzzers

2022-03-05 17:37 UTC, SweetVishnya commented on projects/fmt/build.sh
> +cp -r bin ./sydr
cp -r bin ../sydr

2022-03-05 17:37 UTC, SweetVishnya commented on projects/fmt/build.sh
> +cp -r bin ./cov
cp -r bin ../cov

2022-03-05 17:37 UTC, SweetVishnya commented on projects/fmt/chrono_duration.toml
> +target = "/fmt/build/sydr/fuzzer_chrono_duration @@"
/fmt/sydr/fuzzer_chrono_duration

remove build in other configs?

2022-03-09 09:33 UTC, xcoldhandsx commented on projects/fmt/build.sh
> +# Coverage
Not necessary, rebuild works fine.

2022-03-09 12:03 UTC, SweetVishnya requested changes

2022-03-09 12:03 UTC, SweetVishnya commented on projects/fmt/build.sh
> +CMAKE_BUILD_PARALLEL_LEVEL=6 cmake --build .
$(nproc)

2022-03-09 12:03 UTC, SweetVishnya commented on projects/fmt/build.sh
> +CMAKE_BUILD_PARALLEL_LEVEL=6 cmake --build .
$(nproc)

2022-03-09 12:03 UTC, SweetVishnya commented on projects/fmt/build.sh
> +CMAKE_BUILD_PARALLEL_LEVEL=6 cmake --build .
$(nproc)

2022-03-11 14:08 UTC, merged