Add OpenSSH project
ispras/oss-sydr-fuzz pull request #242
Opened 2024-07-30 17:35 UTC by Avgor46

2024-08-01 22:04 UTC, headshog requested changes

2024-08-02 09:21 UTC, Avgor46 commented on projects/openssh/build.sh
> +SK_NULL=ssh-sk-null.o
Yes, but at this point all variables that are used to compile targets (except compilers) are defined. This improves readability (I suppose)

2024-08-02 09:28 UTC, Avgor46 commented on projects/openssh/README.md
> +
done

2024-08-02 09:37 UTC, headshog approved these changes

2024-08-03 22:51 UTC, merged