[freeimage] Tiff targets for freeimage.
ispras/oss-sydr-fuzz pull request #38
Opened 2022-05-20 15:25 UTC by kobrineli

2022-05-21 08:06 UTC, SweetVishnya requested changes

2022-05-21 08:06 UTC, SweetVishnya commented on projects/freeimage/README.md
> +Collect and report coverage:
There is no coverage binary

2022-05-21 08:06 UTC, SweetVishnya commented on projects/freeimage/load_from_memory_tiff.toml
> +# Copyright 2021 ISP RAS
2022

2022-05-21 08:06 UTC, SweetVishnya commented on projects/freeimage/load_from_memory_tiff.toml
> +args = "-l debug -n 1024 --app-timeout 60"
`-n 1024` -> `-s 90`

2022-05-21 08:06 UTC, SweetVishnya commented on projects/freeimage/load_from_memory_tiff.toml
> +args = "-l debug -n 1024 --app-timeout 60"
Is 60 app timeout enough?

2022-05-23 11:03 UTC, kobrineli commented on projects/freeimage/README.md
> +Collect and report coverage:
done

2022-05-23 11:04 UTC, kobrineli commented on projects/freeimage/load_from_memory_tiff.toml
> +# Copyright 2021 ISP RAS
done

2022-05-23 11:04 UTC, kobrineli commented on projects/freeimage/load_from_memory_tiff.toml
> +args = "-l debug -n 1024 --app-timeout 60"
done

2022-05-23 12:13 UTC, SweetVishnya requested changes

2022-05-23 12:13 UTC, SweetVishnya commented on projects/freeimage/README.md
> +Minimize corpus:
remove minimize corpus (stated twice)

2022-05-23 12:15 UTC, kobrineli commented on projects/freeimage/README.md
> +Minimize corpus:
done

2022-05-23 12:16 UTC, merged