Add PyTorch
ispras/oss-sydr-fuzz pull request #46
Opened 2022-07-06 12:29 UTC by sigseg5

2022-07-06 13:00 UTC, apach301 commented on projects/pytorch/dump_sydr.cc
> +#include <fstream>
Not need in this

2022-07-06 13:07 UTC, apach301 commented on projects/pytorch/README.md
> +* stoull.patch – Added additional caffe2 version check for deeper fuzzing.
miniz.* – Updated miniz version to fix segmentation fault.
stoull.patch – Catch stoull exception to allow the fuzzer go deeper

2022-07-06 14:57 UTC, SweetVishnya requested changes

2022-07-06 14:57 UTC, SweetVishnya commented on projects/pytorch/Dockerfile
> +RUN ln -snf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
Timezone could be set via docker `-v /etc/localtime:/etc/localtime:ro`:

```
sudo docker run --privileged --network host -v /etc/localtime:/etc/localtime:ro --rm -it -v $PWD:/fuzz oss-sydr-fuzz-pytorch /bin/bash
```

2022-07-06 14:57 UTC, SweetVishnya commented on projects/pytorch/README.md
> +* `MAX_JOBS=100` in build_*.sh – The maximum number of jobs to build the whole project, if your machine has fewer threads, the build system will use all the threads.
Why don't we use nproc?

2022-07-06 14:57 UTC, SweetVishnya commented on projects/pytorch/README.md
> +`docker build -t oss-sydr-fuzz-pytorch .`
dollar signs before commands, you may check other READMEs

2022-07-06 14:57 UTC, SweetVishnya commented on projects/pytorch/README.md
> +
cmin, security, casr docs

2022-07-07 10:02 UTC, sigseg5 commented on projects/pytorch/README.md
> +* `MAX_JOBS=100` in build_*.sh – The maximum number of jobs to build the whole project, if your machine has fewer threads, the build system will use all the threads.
Done

2022-07-07 10:07 UTC, SweetVishnya requested changes

2022-07-07 10:07 UTC, SweetVishnya commented on projects/pytorch/README.md
> +* `MAX_JOBS=100` in build_*.sh – The maximum number of jobs to build the whole project, if your machine has fewer threads, the build system will use all the threads.
obsolete comment

2022-07-07 10:15 UTC, SweetVishnya commented on projects/pytorch/README.md
> +## Crash amalysis with Casr
analysis

2022-07-07 10:16 UTC, SweetVishnya commented on projects/pytorch/README.md
> +## Applyed patches
applied

2022-07-07 10:19 UTC, SweetVishnya approved these changes

2022-07-07 10:19 UTC, merged