[tensorflow] AFL++ build
ispras/oss-sydr-fuzz pull request #63
Opened 2022-08-19 12:11 UTC by kobrineli

2022-08-19 17:05 UTC, SweetVishnya requested changes

2022-08-19 17:05 UTC, SweetVishnya commented on projects/tensorflow/make_corporas.sh
> +#!/bin/bash
Remove this file

2022-08-21 17:11 UTC, kobrineli commented on projects/tensorflow/make_corporas.sh
> +#!/bin/bash
done

2022-08-21 17:11 UTC, kobrineli commented on projects/tensorflow/build_afl.sh
> +# Modifications copyright (C) 2021 ISP RAS
done

2022-08-21 17:12 UTC, kobrineli commented on projects/tensorflow/Dockerfile
> +    unzip /status.zip && unzip /stringprintf.zip && unzip /string_replace.zip && unzip /tstring.zip
done

2022-08-22 09:49 UTC, SweetVishnya commented on projects/tensorflow/Dockerfile
> +    unzip /status.zip && unzip /stringprintf.zip && unzip /string_replace.zip && unzip /tstring.zip
rm them in the same command to reduce space used by docker

2022-08-22 11:17 UTC, kobrineli commented on projects/tensorflow/Dockerfile
> +    unzip /status.zip && unzip /stringprintf.zip && unzip /string_replace.zip && unzip /tstring.zip
done

2022-08-22 11:58 UTC, SweetVishnya approved these changes
We'll merge it as soon as your fix PR is in AFL++ stable.

2022-08-25 21:37 UTC, merged