Add torchvision
ispras/oss-sydr-fuzz pull request #70
Opened 2022-08-25 11:15 UTC by sigseg5

2022-08-25 16:26 UTC, anfedotoff commented on projects/vision/decode_jpeg_fuzz.cc
> +      torch::from_file(dir, /*shared=*/false, /*size=*/size_i, torch::kU8);
Is it possible to create tensor from memory?
https://github.com/pytorch/pytorch/blob/a7edf713608806f10e17eab90d0a5df727d9a16e/aten/src/ATen/native/TensorFactories.cpp#L1463

2022-08-25 17:14 UTC, SweetVishnya requested changes

2022-08-25 17:14 UTC, SweetVishnya commented on projects/vision/decode_jpeg_fuzz.cc
> +  if (size <= 2) { return 0; }
size < 2

2022-08-26 09:20 UTC, sigseg5 commented on projects/vision/Dockerfile
> +RUN cd / && mkdir cv && cd cv/ && wget -O opencv.zip https://github.com/opencv/opencv/archive/4.x.zip && unzip opencv.zip && mkdir -p build && cd build && cmake -DBUILD_TESTS=OFF ../opencv-4.x && cma
Done

2022-08-26 09:21 UTC, sigseg5 commented on projects/vision/build_corpus.sh
> +clang++ -DAT_PER_OPERATOR_HEADERS -DCPUINFO_SUPPORTED_PLATFORM=1 -DFMT_HEADER_ONLY=1 -DFXDIV_USE_INLINE_ASSEMBLY=0 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMI
Done all multilines

2022-08-26 09:54 UTC, sigseg5 commented on projects/vision/decode_jpeg_fuzz.cc
> +  if (size <= 2) { return 0; }
Done

2022-08-26 12:43 UTC, sigseg5 commented on projects/vision/Dockerfile
> +RUN cp miniz.* /pytorch_fuzz/third_party/miniz-2.0.8/.
Done

2022-08-26 12:43 UTC, sigseg5 commented on projects/vision/README.md
> +* stoull.patch – Catch stoull exception to allow the fuzzer go deeper.
Done

2022-08-26 14:14 UTC, merged